---
bases:
  - helmfile-common.yaml
---
releases:
  - name: vault-operator
    namespace: {{ .Values.vaultOperator.namespace }}
    chart: banzaicloud/vault-operator
    version: 1.10.1
    wait: true
    atomic: true
