---
bases:
  - helmfile-common.yaml
---
releases:
  - name: vault
    namespace: {{ .Values.vault.namespace }}
    chart: incubator/raw
    version: 0.2.3
    atomic: true
    values:
      - values/vault.yaml.gotmpl
  - name: postgres
    namespace: {{ .Values.vault.namespace }}
    chart: bitnami/postgresql
    version: 10.9.5
    atomic: true
    values:
      - values/postgres.yaml.gotmpl
  - name: quorum-key-manager
    namespace: {{ .Values.qkm.namespace }}
    chart: consensys/quorumkeymanager
    atomic: true
    version: 1.0.13
    needs:
      - {{ .Values.vault.namespace }}/vault
      - {{ .Values.vault.namespace }}/postgres
    values:
      - values/qkm.yaml.gotmpl
