---
bases:
  - helmfile-common.yaml
---
releases:
  - name: postgres
    namespace: {{ .Values.qkm.namespace }}
    chart: bitnami/postgresql
    version: 10.15.0
    atomic: true
    values:
      - values/postgres.yaml.gotmpl
  - name: quorum-key-manager
    namespace: {{ .Values.qkm.namespace }}
    chart: {{ .Values.qkm.chart.name }}
    atomic: true
    version: {{ .Values.qkm.chart.version }}
    needs:
      - {{ .Values.qkm.namespace }}/postgres
    values:
      - values/qkm.yaml.gotmpl
