---
bases:
  - helmfile-common.yaml
---
releases:
  - name: postgres
    namespace: {{ .Values.qkm.namespace }}
    chart: bitnami/postgresql
    version: 10.9.5
    atomic: true
    values:
      - values/postgres.yaml.gotmpl
  - name: quorum-key-manager
    namespace: {{ .Values.qkm.namespace }}
    chart: consensys/quorumkeymanager
    atomic: true
    version: 1.1.4
    needs:
      - {{ .Values.qkm.namespace }}/postgres
    values:
      - values/qkm.yaml.gotmpl
