observability:
  enabled: false
vault:
  nodeSelector: vault
  dedicatedNode: false
  tls:
    enabled: true
    skipVerify: false
  audit:
    enabled: false
postgresql:
  tls:
    enabled: true
  Database: testDb
auth:
  apikey:
    enabled: true
    file: "/apikey/sample.csv"
  oidc:
    enabled: true
  tls:
    enabled: true
    secretName: "qkm-tls"