- kind: Vault
    type: azure
    name: akv-europe
    # allowed_tenants: [tenant1, tenant2]
    specs:
      vault_name: ${QKM_AKV_VAULT_NAME}
      tenant_id: ${QKM_AKV_TENANT_ID}
      client_id: ${QKM_AKV_CLIENT_ID}
      client_secret: ${QKM_AKV_CLIENT_SECRET}
  - kind: Vault
    type: aws
    name: aws-europe
    # allowed_tenants: [tenant1, tenant2]
    specs:
      access_id: ${QKM_AWS_ACCESS_ID}
      secret_key: ${QKM_AWS_SECRET_KEY}
      region: ${QKM_AWS_REGION}
  - kind: Store
    type: key
    name: akv-keys
    # allowed_tenants: []
    specs:
      vault: akv-europe
  - kind: Store
    type: secret
    name: akv-secrets
    # allowed_tenants: []
    specs:
      vault: akv-europe
  - kind: Store
    type: key
    name: aws-keys
    # allowed_tenants: []
    specs:
      vault: aws-europe
  - kind: Store
    type: secret
    name: aws-secrets
    # allowed_tenants: []
    specs:
      vault: aws-europe
  - kind: Store
    type: ethereum
    name: eth-accounts
    # allowed_tenants: []
    specs:
      key_store: akv-keys
  - kind: Node
    name: quorum-node
    specs:
      rpc:
        addr: ${QUORUM_URL}
      tessera:
        addr: ${TESSERA_URL}
  - kind: Node
    name: besu-node
    specs:
      rpc:
        addr: ${BESU_URL}

  - kind: Node
    name: geth-node
    specs:
      rpc:
        addr: ${GETH_URL}
  - kind: Role
    name: anonymous
    specs:
      permissions:
        - "proxy:nodes"

  - kind: Role
    name: guest
    specs:
      permissions:
        - "read:*"

  - kind: Role
    name: signer
    specs:
      permissions:
        - "read:*"
        - "sign:keys"
        - "sign:ethereum"

  - kind: Role
    name: admin
    specs:
      permissions:
        - "*:*"